
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import 'GameUnit.sol';


contract warior is GameUnit{
    
    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }
     //- получить силу атаки
    function atacLevel(uint volue) public override {
        tvm.accept();
        impactforce  = impactforce + volue;
    }

    //- получить силу защиты
    function plusprotection(uint voluepr) public override {
        tvm.accept();
        protection = protection + voluepr;
    }
   
}
